name: container
on:
  push:
    branches:
      -  develop
jobs:
  container_job:
    runs-on: ubuntu-latest
    container:
      image: node:14-alpine3.12
    steps:
      - name: Log the node version in container
        run: |
          node -v 
          cat /etc/os-release