name: matrix
on:
  push:
    branches:
      - develop
jobs:
  version:
    strategy:
      matrix: 
        os: [macos-latest, windows-latest,ubuntu-latest]
        node_version: [6, 7, 8]
        include:
          - os: windows-latest
            node_version: 6
            is_true: "dharmi"
        exclude:
          - os: ubuntu-latest
            node_version: 7
          - os: macos-latest
            node_version: 8
    runs-on: ${{matrix.os}}
    env:
      IS_TRUE : ${{matrix.is_true}}
    steps:
      - name: check node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
      - name: check node version
        run: | 
          node -v
          echo ${IS_TRUE}
        