name: matrix
on:
  push:
    branches:
      - develop
jobs:
  version:
    strategy:
      matrix: 
        os: [macos-latest, windows-latest,ubuntu-latest]
        node_version: [6, 7, 8]
    runs-on: ${{matrix.os}}
    steps:
      - name: check node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
      - name: check node version
        run: node -v
        