name: nodjs_container
on: 
  push:
    branches:
      - develop
jobs:
  node_container:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a user
        run: "curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d ' {\"username\":\"dharmi\",\"address\":\"trichy\"} '"
      - name: Get Users
        run: "curl http://localhost:3001/api/users"
