name: secrets 
on:
  push:
    branches:
      -  master
jobs:
  my_secret:
    runs-on: ubuntu-latest
    steps:
      - name: get secret - decrypt
        env:
          PASSPHRASE: "{{secrets.PASSPHRASE}}"
        uses: actions/checkout@v1
        run: gpg --quiet --batch --yes --decrypt --output $HOME/secret.json secret.json.gpg
      - name: display contents
        run : cat $HOME/secret.json
      

