name: secrets 
on:
  push:
    branches:
      -  master
jobs:
  my_secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: directory
        run: |
          pwd
          ls -a
      - name: get secret - decrypt
        env:
          PASSPHRASE: "{{secrets.PASSPHRASE}}"
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secret.json secret.json.gpg
      - name: display contents
        run : cat $HOME/secret.json
      

