name: shell commands
on:
  # schedule:
  #   - cron: "0/5 * * * *"
  push:
    branches:
      - master
    tags:
      - v1.*
    paths:
      - "**.yml"
jobs:
  run-command-shell:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo dharmi da
      - name: multilinetext
        run: |
          node -v
          npm -v
  run-on-windows:
    runs-on: windows-latest
    needs: ['run-command-shell']
    steps:
      - name: ps directory
        run: Get-Location
      - name: bash directory
        run: pwd
        shell: bash

