name: shell commands
on: push
jobs:
  run-command-shell:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo dharmi da
      - name: multilinetext
        run: |
          node -v
          npm -v
  run-on-windows:
    runs-on: windows-latest
    steps:
      - name: ps directory
        run: Get-Location
      - name: bash directory
        run: pwd
        shell: bash

